# Generated by Django 3.2.9 on 2022-01-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220103_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='text',
            new_name='content',
        ),
    ]
